# Generated by Django 5.2.1 on 2025-05-23 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genba_manager_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='end_time',
            field=models.TimeField(default='17:00', verbose_name='作業終了時間'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='start_time',
            field=models.TimeField(default='08:00', verbose_name='作業開始時間'),
        ),
    ]
